### PR TITLE
Develop - add DE

### PR DESCRIPTION
**Pull request by dmylonas**
Jon, I did the corrections sent by our collaborator yesterday but I couldn't see them at dev.
should be fine, I hope

### CODE REVIEW

**Comment by jstutters** [comment]
@dmylonas Those changes seem to be on develop for me.  Remember it takes about 5 minutes for a commit to be reflected on the site.

**Comment by dmylonas** [comment]
@jstutters even today I cannot see them in the develop.

**Comment by jstutters** [comment]
@dmylonas do you mean the change to the English text in name_colours.html?  Altering the English version in the msgid string of messages.pot won’t change the displayed text.

**Comment by dmylonas** [comment]
Can you see the German translation at the master site? I can't. I cannot see the changes of 'update DE trans' at the dev either

**Comment by dmylonas** [comment]
@jstutters the English is fine, the German is my problem.

**Pull request merged**
