### PR TITLE
Implement thank you page

### PR DESCRIPTION
**Pull request by chrisguttandin**
This pull request adds the implementation to display the dynamic data on the thank-you page.

### CODE REVIEW

**Comment by jstutters** [comment]
I think we need some formatting on the percentage string...

float_format_prob

**Comment by jstutters** [comment]
Also, should there be a link back to the front page @dmylonas?

**Comment by dmylonas** [comment]
please do not use decimals 33% will be fine. Most of our existing participants named 20 samples.

**Comment by chrisguttandin** [comment]
The values are now displayed without any decimals. This pull request resolve #9 and will also resolve #8.

**Comment by dmylonas** [comment]
We used to have a 'continue' button in the design of the thank you page that was supposed to take you back to the naming task to continue naming colours and 'improve your performance' but at some point we dropped it as I thought that users can use the back buttons of their browsers to do it if they wish to. 
If it is easy to implement (continue counting), we could add one at the end of the page after the results
'You can also continue naming colours to improve your performance'
((continue)) ->similar to the Results button

What is your view?

**Pull request merged**
